export const products = [
  {
    id: 1,
    name: "Silk Evening Gown",
    price: 450,
    category: "dresses",
    image: "/elegant-silk-evening-gown-black-gold.jpg",
    description: "Luxurious silk evening gown with intricate detailing",
    sex: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "gold"],
    stock: 8,
  },
  {
    id: 2,
    name: "Premium Wool Coat",
    price: 680,
    category: "outerwear",
    image: "/premium-wool-coat-luxury-beige.jpg",
    description: "Classic premium wool coat perfect for any occasion",
    sex: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["beige", "brown"],
    stock: 0,
  },
  {
    id: 3,
    name: "Cashmere Sweater",
    price: 320,
    category: "tops",
    image: "/luxurious-cashmere-sweater-cream.jpg",
    description: "Soft cashmere sweater for ultimate comfort",
    sex: "women",
    sizes: ["S", "M", "L"],
    colors: ["cream", "white"],
    stock: 12,
  },
  {
    id: 4,
    name: "Designer Blazer",
    price: 550,
    category: "blazers",
    image: "/tailored-designer-blazer-gold-trim.jpg",
    description: "Perfectly tailored designer blazer with gold accents",
    sex: "men",
    sizes: ["M", "L", "XL"],
    colors: ["navy", "black"],
    stock: 6,
  },
  {
    id: 5,
    name: "Silk Trousers",
    price: 280,
    category: "bottoms",
    image: "/elegant-silk-trousers-black.jpg",
    description: "Elegant silk trousers with perfect fit",
    sex: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "charcoal"],
    stock: 10,
  },
  {
    id: 6,
    name: "Leather Accessories",
    price: 195,
    category: "accessories",
    image: "/luxury-leather-accessories-beige.jpg",
    description: "Premium leather accessories collection",
    sex: "unisex",
    sizes: [],
    colors: ["beige", "tan"],
    stock: 20,
  },
  {
    id: 7,
    name: "Linen Dress",
    price: 380,
    category: "dresses",
    image: "/premium-linen-dress-cream.jpg",
    description: "Breathable linen dress with timeless elegance",
    sex: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["cream", "white"],
    stock: 7,
  },
  {
    id: 8,
    name: "Designer Bag",
    price: 890,
    category: "accessories",
    image: "/luxury-designer-handbag-gold-chain.jpg",
    description: "Exclusive designer handbag with gold hardware",
    sex: "women",
    sizes: [],
    colors: ["black", "gold"],
    stock: 4,
  },
]

export const bestSellers = [products[0], products[1], products[3], products[7]]

export const sales = [
  { ...products[2], originalPrice: 450 },
  { ...products[4], originalPrice: 380 },
]
